set -g status-interval 5
set -g default-terminal "screen-256color"
# set -g status-right "#(ping -c 1 -W 1 8.8.8.8 > /dev/null && echo '😊' || echo '😈') | %H:%M"
# 灰紫色调，视觉疲劳度低
set -g status-style "bg=#5f3182,fg=#ffffff"

setw -g mode-keys vi

# for codex-cli copy
# v: 矩形选择
bind -T copy-mode-vi v send -X begin-selection -r
# y: 复制并退出 copy-mode，然后切到左 pane 并粘贴
bind -T copy-mode-vi y \
  send -X copy-selection-and-cancel \; \
  select-pane -L \; \
  paste-buffer


# 非当前 pane 显示：pane id + 标题
set -gu pane-border-format " #P #{pane_title} "

# 当前 pane 高亮显示
set -g pane-active-border-style ""
set -g pane-border-style "fg=colour240"
# 在状态栏左侧显示：window索引:window名 [pane编号]
set -g pane-border-status top
set -g pane-border-format "P:#P "


# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'dracula/tmux'
set -g @dracula-plugins "battery network weather time"
set -g @dracula-show-left-icon "😛 #S"
set -g @dracula-network-ethernet-label "😊"
set -g @dracula-network-offline-label "😈"
set -g @dracula-network-hosts "8.8.8.8"
set -g @dracula-day-month true
set -g @dracula-time-format "%H:%M"
set -g @dracula-fixed-location "Beijing"
run '~/.tmux/plugins/tpm/tpm'
